# 2. Sales Prediction
# A company has determined that its annual profit is typically 23 percent of 
# total sales. Write a program that asks the user to enter the projected amount
# of total sales, and then displays the profit that will be made from that 
# amount. Hint: use the value 0.23 to represent 23 percent
s=float(input("Please enter amount of total sales:"))
p=s*0.23
print("You enter total amount of sales is:",s)
print("Your annual profit is:",p)